package jp.co.soramitsu.common.irohaconnect

import java.net.URLEncoder
import java.nio.charset.StandardCharsets
import jp.co.soramitsu.common.nexus.IrohaKeyDerivation
import jp.co.soramitsu.common.nexus.NexusNetworks
import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test

class IrohaConnectProtocolTest {
    @Test
    fun `launch accepts both schemes but only current network-bound v1 fields`() {
        val fixture = launchFixture("irohaconnect", "")
        val parsed = IrohaConnectUri.parse(fixture.uri)

        assertEquals(NexusNetworks.taira, parsed.network)
        assertArrayEquals(fixture.sid, parsed.sid)
        assertArrayEquals(fixture.appKeys.publicKey, parsed.appPublicKey)
        assertArrayEquals(fixture.nonce, parsed.nonce)
        assertEquals(
            "wss://taira.sora.org/v1/connect/ws?sid=${IrohaConnectEncoding.base64Url(fixture.sid)}&role=wallet",
            parsed.webSocketUri.toString(),
        )
        assertTrue(parsed.tokenProtocol.startsWith("iroha-connect.token.v1."))

        assertThrows(IrohaConnectUriException::class.java) {
            IrohaConnectUri.parse(fixture.uri + "&chain_id=fc56984b-2be7-431d-840e-21514d1883f0")
        }
        assertThrows(IrohaConnectUriException::class.java) {
            IrohaConnectUri.parse(
                fixture.uri + "&sid=${IrohaConnectEncoding.base64Url(fixture.sid)}",
            )
        }
        assertThrows(IrohaConnectUriException::class.java) {
            IrohaConnectUri.parse(
                fixture.uri.replace("node=", "node=${query("https://evil.example")}"),
            )
        }
        assertThrows(IrohaConnectUriException::class.java) {
            IrohaConnectUri.parse(fixture.uri.replace("sid=", "sid=A"))
        }
        assertThrows(IrohaConnectUriException::class.java) {
            IrohaConnectUri.parse(" ${fixture.uri}")
        }
        assertThrows(IrohaConnectUriException::class.java) {
            IrohaConnectUri.parse(fixture.uri.replace("irohaconnect://connect", "irohaconnect://connect/"))
        }
        fixture.appKeys.destroy()
    }

    @Test
    fun `open frame matches canonical iroha js connect browser vector`() {
        // Generated by @iroha/iroha-js/connect-browser at Iroha f082ead6cf1409a437132590425dc50ad06a0e82.
        val sid = IrohaConnectEncoding.base64UrlDecode(
            "rEMIq7ppuNCm2EXcg5v_UIzNE4IX2g8AeGEtPIPCVhU",
            32,
        )
        val appPublicKey = IrohaConnectEncoding.hexDecode(
            "07a37cbc142093c8b755dc1b10e86cb426374ad16aa853ed0bdfc0b2b86d1c7c",
        )
        val permissions = IrohaConnectPermissions(
            methods = listOf("sign_raw"),
            events = emptyList(),
            resources = listOf("uranai.contract-call.v1"),
        )
        val encoded = IrohaConnectWire.encodeOpen(
            sid = sid,
            appPublicKey = appPublicKey,
            networkIdBytes = IrohaNetworkId.parse(TairaNetworkId.literal),
            appMetadata = IrohaConnectAppMetadata(
                name = "Uranai",
                url = "https://uranai.sora.org",
                iconHash = null,
            ),
            permissions = permissions,
        )
        val canonical = IrohaConnectEncoding.hexDecode(
            """
            2000000000000000ac4308abba69b8d0a6d845dc839bff508ccd138217da0f0078612d3c83c25615
            04000000000000000000000008000000000000000100000000000000590100000000000000000000
            4d01000000000000000000004101000000000000200000000000000007a37cbc142093c8b755dc1b
            10e86cb426374ad16aa853ed0bdfc0b2b86d1c7c5800000000000000014f000000000000000e0000
            000000000006000000000000005572616e61692800000000000000011f0000000000000017000000
            0000000068747470733a2f2f7572616e61692e736f72612e6f726701000000000000000028000000
            00000000200000000000000082531ce8eae8bff6beeca4698bfd13a3bc8bec5f0ee0d23d428c97f
            c17ab0f3b8100000000000000017800000000000000200000000000000001000000000000001000
            00000000000008000000000000007369676e5f726177080000000000000000000000000000003800
            000000000000012f0000000000000001000000000000001f000000000000001700000000000000
            7572616e61692e636f6e74726163742d63616c6c2e7631
            """.filterNot(Char::isWhitespace),
        )
        assertArrayEquals(canonical, encoded)

        val open = (IrohaConnectWire.decodeFrame(canonical) as IrohaConnectFrame.Control)
            .control as IrohaConnectControl.Open
        assertArrayEquals(appPublicKey, open.appPublicKey)
        assertEquals("Uranai", open.appMetadata?.name)
        assertEquals(permissions, open.permissions)
    }

    @Test
    fun `approval preimage and signature match the shared Iroha fixture`() {
        val networkId = ByteArray(32) { 0x41 }
        val sid = IrohaConnectEncoding.hexDecode(
            "3585891bdcb97bcf2e82617641940fedd4c2c0be946d21b603c60dbcfa57f4b2",
        )
        val appPublicKey = ByteArray(32) { 0x01 }
        val walletPublicKey = ByteArray(32) { 0x03 }
        val accountId = "sorauﾛ1Pｺeﾌﾑ8ﾋS8ヰｵhﾉｱGﾍ2u7ﾌ2WFkUﾘbp7aｵoｽﾎヰﾍ3ﾂ5U68ND6"
        val preimage = IrohaConnectApprovalPreimage.modern(
            networkId,
            sid,
            appPublicKey,
            walletPublicKey,
            accountId,
            "relay-token-vector",
            null,
        )

        assertEquals(449, preimage.size)
        assertEquals(
            "d3188403ad8c059b5c7251817ed6a617b614366565c1ac2a7853b536dbf56de6",
            IrohaConnectEncoding.hex(IrohaConnectCrypto.sha256(preimage)),
        )
        assertEquals(
            "694564115372e4b89c6c9a58bb144927adc8562498423e7bc3f5c87ae5ea733f" +
                "0626093446442f78fbc4fdf642bb1dacacbb7220f190705ed041c7bf2ec9240a",
            IrohaConnectEncoding.hex(
                IrohaConnectCrypto.signEd25519(ByteArray(32) { 0x44 }, preimage),
            ),
        )

        val approval = IrohaConnectWire.encodeApproval(
            sid = sid,
            sequence = 1,
            walletPublicKey = walletPublicKey,
            accountId = accountId,
            permissions = null,
            signature = IrohaConnectCrypto.signEd25519(ByteArray(32) { 0x44 }, preimage),
        )
        val canonicalApproval = IrohaConnectEncoding.hexDecode(
            """
            20000000000000003585891bdcb97bcf2e82617641940fedd4c2c0be946d21b603c60dbcfa57f4b2
            040000000000000001000000080000000000000001000000000000001b0100000000000000000000
            0f010000000000000100000003010000000000002000000000000000030303030303030303030303
            030303030303030303030303030303030303030360000000000000005800000000000000736f7261
            75efbe9b3150efbdba65efbe8cefbe9138efbe8b5338e383b0efbdb568efbe89efbdb147efbe8d32
            7537efbe8c3257466b55efbe9862703761efbdb56fefbdbdefbe8ee383b0efbe8d33efbe823555363
            84e4436010000000000000000010000000000000000590000000000000001000000000000000048
            000000000000004000000000000000694564115372e4b89c6c9a58bb144927adc8562498423e7bc
            3f5c87ae5ea733f0626093446442f78fbc4fdf642bb1dacacbb7220f190705ed041c7bf2ec9240a
            """.filterNot(Char::isWhitespace),
        )
        assertArrayEquals(canonicalApproval, approval)

        val scopedPreimage = IrohaConnectApprovalPreimage.modern(
            networkId,
            sid,
            appPublicKey,
            walletPublicKey,
            accountId,
            "relay-token-vector",
            IrohaConnectPermissions(
                methods = listOf("sign_raw"),
                events = emptyList(),
                resources = listOf(URANAI_SIGNING_DOMAIN),
            ),
        )
        assertEquals(502, scopedPreimage.size)
        assertEquals(
            "e632fcbe0087735dd8965eb07594b0d0227bb5de7b7c2accfa73aad60482f172",
            IrohaConnectEncoding.hex(IrohaConnectCrypto.sha256(scopedPreimage)),
        )
        preimage.fill(0)
        scopedPreimage.fill(0)
        approval.fill(0)
    }

    @Test
    fun `current envelope uses canonical schema and authenticated round trip`() {
        val message = ByteArray(32) { index -> (index + 1).toByte() }
        val encoded = IrohaConnectEnvelopeWire.encode(
            2,
            IrohaConnectEnvelopePayload.SignRaw("FI_PROPOSAL_SIGN", message),
        )
        assertEquals(
            "4e52543000006947afe3e8a85446d6a3ee7bb1a37c0a",
            IrohaConnectEncoding.hex(encoded.copyOfRange(0, 22)),
        )
        val decoded = IrohaConnectEnvelopeWire.decode(encoded)
        assertEquals(2, decoded.sequence)
        val raw = decoded.payload as IrohaConnectEnvelopePayload.SignRaw
        assertEquals("FI_PROPOSAL_SIGN", raw.domainTag)
        assertArrayEquals(message, raw.message)

        val key = ByteArray(32) { (it + 9).toByte() }
        val sid = ByteArray(32) { (it + 45).toByte() }
        val ciphertext = IrohaConnectCrypto.encrypt(
            key,
            2,
            IrohaConnectWire.associatedData(sid, IrohaConnectDirection.APP_TO_WALLET, 2),
            encoded,
        )
        val authenticated = IrohaConnectEnvelopeWire.decrypt(
            key,
            sid,
            IrohaConnectDirection.APP_TO_WALLET,
            2,
            ciphertext,
        )
        assertEquals(2, authenticated.sequence)

        ciphertext[0] = (ciphertext[0].toInt() xor 1).toByte()
        assertThrows(Exception::class.java) {
            IrohaConnectEnvelopeWire.decrypt(
                key,
                sid,
                IrohaConnectDirection.APP_TO_WALLET,
                2,
                ciphertext,
            )
        }
    }

    @Test
    fun `session binds open approval permission request and signed response`() {
        val fixture = launchFixture("iroha", "https://taira.sora.org")
        val launch = IrohaConnectUri.parse(fixture.uri)
        val session = IrohaConnectWalletSession(launch, startedAtMillis = 1_000)
        val permissionDomain = URANAI_SIGNING_DOMAIN
        val permissions = IrohaConnectPermissions(
            methods = listOf("sign_raw"),
            events = emptyList(),
            resources = listOf(permissionDomain),
        )
        val open = IrohaConnectWire.encodeOpen(
            sid = launch.sid,
            appPublicKey = launch.appPublicKey,
            networkIdBytes = launch.networkIdBytes,
            appMetadata = IrohaConnectAppMetadata(
                name = "Uranai",
                url = "https://uranai.sora.org",
                iconHash = null,
            ),
            permissions = permissions,
        )
        val pairing = session.receive(open, 1_100) as IrohaConnectSessionEvent.PairingRequested
        assertEquals("Uranai", pairing.review.appName)
        assertEquals(listOf(permissionDomain), pairing.review.permissions?.resources)

        val account = IrohaKeyDerivation.derive(MNEMONIC, NexusNetworks.taira)
        try {
            val approvalEvent = session.approvePairing(account.address, 1_200) {
                IrohaConnectCrypto.signEd25519(account.privateKeySeed, it)
            }
            val approval = IrohaConnectWire.decodeFrame(approvalEvent.bytes)
                as IrohaConnectFrame.Control
            assertEquals(1, approval.sequence)
            assertEquals(IrohaConnectDirection.WALLET_TO_APP, approval.direction)
            val approvalControl = approval.control as IrohaConnectControl.Approve
            assertEquals(account.address, approvalControl.accountId)
            assertEquals(permissions, approvalControl.permissions)

            val appDirectionKeys = IrohaConnectCrypto.deriveDirectionKeys(
                sid = launch.sid,
                appPublicKey = approvalControl.walletPublicKey,
                walletPrivateKey = fixture.appKeys.privateKey,
            )
            try {
                val message = "sign this contract call".toByteArray()
                val requestEnvelope = IrohaConnectEnvelopeWire.encode(
                    2,
                    IrohaConnectEnvelopePayload.SignRaw(permissionDomain, message),
                )
                val requestCiphertext = IrohaConnectCrypto.encrypt(
                    appDirectionKeys.appToWallet,
                    2,
                    IrohaConnectWire.associatedData(
                        launch.sid,
                        IrohaConnectDirection.APP_TO_WALLET,
                        2,
                    ),
                    requestEnvelope,
                )
                val requestFrame = IrohaConnectWire.encodeCiphertext(
                    launch.sid,
                    2,
                    requestCiphertext,
                    IrohaConnectDirection.APP_TO_WALLET,
                )
                val request = session.receive(requestFrame, 1_300)
                    as IrohaConnectSessionEvent.SigningRequested
                assertEquals(IrohaConnectSigningKind.RAW, request.review.kind)
                assertEquals(permissionDomain, request.review.domainTag)
                assertEquals(String(message, Charsets.UTF_8), request.review.readableMessage)

                val concurrentEnvelope = IrohaConnectEnvelopeWire.encode(
                    3,
                    IrohaConnectEnvelopePayload.SignRaw(
                        permissionDomain,
                        "must not replace the pending request".toByteArray(),
                    ),
                )
                val concurrentCiphertext = IrohaConnectCrypto.encrypt(
                    appDirectionKeys.appToWallet,
                    3,
                    IrohaConnectWire.associatedData(
                        launch.sid,
                        IrohaConnectDirection.APP_TO_WALLET,
                        3,
                    ),
                    concurrentEnvelope,
                )
                val concurrentFrame = IrohaConnectWire.encodeCiphertext(
                    launch.sid,
                    3,
                    concurrentCiphertext,
                    IrohaConnectDirection.APP_TO_WALLET,
                )
                val concurrentResponse = session.receive(concurrentFrame, 1_350)
                    as IrohaConnectSessionEvent.SendFrame
                assertFalse(concurrentResponse.signed)
                val concurrentResponseFrame = IrohaConnectWire.decodeFrame(concurrentResponse.bytes)
                    as IrohaConnectFrame.Ciphertext
                val concurrentError = IrohaConnectEnvelopeWire.decrypt(
                    appDirectionKeys.walletToApp,
                    launch.sid,
                    IrohaConnectDirection.WALLET_TO_APP,
                    2,
                    concurrentResponseFrame.aead,
                ).payload as IrohaConnectEnvelopePayload.SignResultError
                assertEquals("REQUEST_IN_FLIGHT", concurrentError.code)

                assertThrows(IrohaConnectSessionException::class.java) {
                    session.approveRequest("wrong-token", 1_400) {
                        IrohaConnectCrypto.signEd25519(account.privateKeySeed, it)
                    }
                }
                val responseEvent = session.approveRequest(request.review.requestToken, 1_400) {
                    IrohaConnectCrypto.signEd25519(account.privateKeySeed, it)
                }
                assertTrue(responseEvent.signed)
                val response = IrohaConnectWire.decodeFrame(responseEvent.bytes)
                    as IrohaConnectFrame.Ciphertext
                val responseEnvelope = IrohaConnectEnvelopeWire.decrypt(
                    appDirectionKeys.walletToApp,
                    launch.sid,
                    IrohaConnectDirection.WALLET_TO_APP,
                    3,
                    response.aead,
                )
                val result = responseEnvelope.payload as IrohaConnectEnvelopePayload.SignResultOk
                assertTrue(
                    IrohaConnectCrypto.verifyEd25519(
                        account.publicKey,
                        message,
                        result.signature.signature,
                    ),
                )

                assertThrows(IrohaConnectSessionException::class.java) {
                    session.receive(requestFrame, 1_500)
                }

                val deniedEnvelope = IrohaConnectEnvelopeWire.encode(
                    4,
                    IrohaConnectEnvelopePayload.SignRaw(
                        "uranai.irohaconnect.unapproved-domain.v1",
                        "must not be signed".toByteArray(),
                    ),
                )
                val deniedCiphertext = IrohaConnectCrypto.encrypt(
                    appDirectionKeys.appToWallet,
                    4,
                    IrohaConnectWire.associatedData(
                        launch.sid,
                        IrohaConnectDirection.APP_TO_WALLET,
                        4,
                    ),
                    deniedEnvelope,
                )
                val deniedFrame = IrohaConnectWire.encodeCiphertext(
                    launch.sid,
                    4,
                    deniedCiphertext,
                    IrohaConnectDirection.APP_TO_WALLET,
                )
                val deniedResponse = session.receive(deniedFrame, 1_550)
                    as IrohaConnectSessionEvent.SendFrame
                assertFalse(deniedResponse.signed)
                val deniedResponseFrame = IrohaConnectWire.decodeFrame(deniedResponse.bytes)
                    as IrohaConnectFrame.Ciphertext
                val deniedError = IrohaConnectEnvelopeWire.decrypt(
                    appDirectionKeys.walletToApp,
                    launch.sid,
                    IrohaConnectDirection.WALLET_TO_APP,
                    4,
                    deniedResponseFrame.aead,
                ).payload as IrohaConnectEnvelopePayload.SignResultError
                assertEquals("PERMISSION_DENIED", deniedError.code)

                val closeFrame = IrohaConnectWire.decodeFrame(
                    requireNotNull(session.closeWithFrame("Interop test complete")),
                ) as IrohaConnectFrame.Ciphertext
                assertEquals(5, closeFrame.sequence)
                val closeEnvelope = IrohaConnectEnvelopeWire.decrypt(
                    appDirectionKeys.walletToApp,
                    launch.sid,
                    IrohaConnectDirection.WALLET_TO_APP,
                    5,
                    closeFrame.aead,
                )
                assertEquals(
                    "Interop test complete",
                    (closeEnvelope.payload as IrohaConnectEnvelopePayload.Close).reason,
                )
            } finally {
                appDirectionKeys.destroy()
            }
        } finally {
            session.close()
            account.destroy()
            fixture.appKeys.destroy()
        }
        assertTrue(session.isClosed)
    }

    @Test
    fun `unsupported transaction and unreadable raw payload never invoke signer`() {
        listOf(false, true).forEach { transaction ->
            val fixture = launchFixture("iroha", "https://taira.sora.org")
            val launch = IrohaConnectUri.parse(fixture.uri)
            val session = IrohaConnectWalletSession(launch, startedAtMillis = 1_000)
            val account = IrohaKeyDerivation.derive(MNEMONIC, NexusNetworks.taira)
            try {
                val permissions = IrohaConnectPermissions(
                    methods = listOf(if (transaction) "sign_transaction" else "sign_raw"),
                    events = emptyList(),
                    resources = if (transaction) null else listOf(URANAI_SIGNING_DOMAIN),
                )
                val open = IrohaConnectWire.encodeOpen(launch.sid, launch.appPublicKey,
                    launch.networkIdBytes, IrohaConnectAppMetadata("Example", "https://example.com", null), permissions)
                session.receive(open, 1_100)
                val approval = IrohaConnectWire.decodeFrame(session.approvePairing(account.address, 1_200) {
                    IrohaConnectCrypto.signEd25519(account.privateKeySeed, it)
                }.bytes) as IrohaConnectFrame.Control
                val walletKey = (approval.control as IrohaConnectControl.Approve).walletPublicKey
                val keys = IrohaConnectCrypto.deriveDirectionKeys(launch.sid, walletKey, fixture.appKeys.privateKey)
                try {
                    val payload = if (transaction) IrohaConnectEnvelopePayload.SignTransaction("opaque transaction".toByteArray())
                        else IrohaConnectEnvelopePayload.SignRaw(URANAI_SIGNING_DOMAIN, byteArrayOf(1, 2, 3))
                    val ciphertext = IrohaConnectCrypto.encrypt(keys.appToWallet, 2,
                        IrohaConnectWire.associatedData(launch.sid, IrohaConnectDirection.APP_TO_WALLET, 2),
                        IrohaConnectEnvelopeWire.encode(2, payload))
                    val request = session.receive(IrohaConnectWire.encodeCiphertext(launch.sid, 2,
                        ciphertext, IrohaConnectDirection.APP_TO_WALLET), 1_300) as IrohaConnectSessionEvent.SigningRequested
                    assertEquals(null, request.review.readableMessage)
                    var signerCalled = false
                    val result = session.approveRequest(request.review.requestToken, 1_400) {
                        signerCalled = true
                        IrohaConnectCrypto.signEd25519(account.privateKeySeed, it)
                    }
                    assertFalse(signerCalled)
                    assertFalse(result.signed)
                    val frame = IrohaConnectWire.decodeFrame(result.bytes) as IrohaConnectFrame.Ciphertext
                    val error = IrohaConnectEnvelopeWire.decrypt(keys.walletToApp, launch.sid,
                        IrohaConnectDirection.WALLET_TO_APP, 2, frame.aead).payload as IrohaConnectEnvelopePayload.SignResultError
                    assertEquals("UNSUPPORTED_SIGNING_CONTENT", error.code)
                } finally { keys.destroy() }
            } finally { session.close(); account.destroy(); fixture.appKeys.destroy() }
        }
    }

    @Test
    fun `low order x25519 peer key is rejected`() {
        assertThrows(IllegalArgumentException::class.java) {
            IrohaConnectCrypto.deriveDirectionKeys(
                sid = ByteArray(32) { 1 },
                appPublicKey = ByteArray(32),
                walletPrivateKey = ByteArray(32) { 2 },
            )
        }
    }

    private data class LaunchFixture(
        val uri: String,
        val sid: ByteArray,
        val nonce: ByteArray,
        val appKeys: IrohaConnectEphemeralKeys,
    )

    private fun launchFixture(scheme: String, node: String): LaunchFixture {
        val keys = IrohaConnectCrypto.ephemeralX25519()
        val nonce = ByteArray(16) { (it + 1).toByte() }
        val networkId = TairaNetworkId.literal
        val networkBytes = IrohaNetworkId.parse(networkId)
        val sid = IrohaConnectCrypto.blake2b256(
            "iroha-connect|sid|".toByteArray() + networkBytes + keys.publicKey + nonce,
        )
        val token = IrohaConnectEncoding.base64Url(ByteArray(32) { 0x11 })
        val relay = IrohaConnectEncoding.base64Url(ByteArray(32) { 0x22 })
        val uri = "$scheme://connect" +
            "?sid=${IrohaConnectEncoding.base64Url(sid)}" +
            "&network_id=${query(networkId)}" +
            "&app_pk=${IrohaConnectEncoding.base64Url(keys.publicKey)}" +
            "&nonce=${IrohaConnectEncoding.base64Url(nonce)}" +
            "&node=${query(node)}" +
            "&v=1&role=wallet&token=$token&relay=$relay"
        return LaunchFixture(uri, sid, nonce, keys)
    }

    private fun query(value: String): String =
        URLEncoder.encode(value, StandardCharsets.UTF_8.name()).replace("+", "%20")

    private object TairaNetworkId {
        const val literal =
            "hash:82531CE8EAE8BFF6BEECA4698BFD13A3BC8BEC5F0EE0D23D428C97FC17AB0F3B#3E94"
    }

    private companion object {
        const val MNEMONIC =
            "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
        const val URANAI_SIGNING_DOMAIN =
            "uranai.irohaconnect.contract-call-signature.v1"
    }
}
