[versions]
agp = "8.2.0"
kotlin = "1.9.10"
appcompat = "1.6.1"
coroutines = "1.7.3"
coreKtx = "1.12.0"
constraint = "2.2.0-alpha05"
biometric = "1.1.0"
navigation = "2.5.0"
navigationCompose = "2.7.5"
lottie = "4.2.0"
insetter = "0.6.1"
workManager = "2.8.1"
coil = "2.2.2"
svg = "1.4"
jdenticon = "1.1"
archFragmentTest = "1.4.1"
mockk = "1.13.8"
truth = "1.1.5"
mockitoKotlin = "5.1.0"
mockito = "5.2.0"
junit = "4.13.2"
androidxTestExtJunit = "1.1.5"
androidxTestEspressoCore = "3.5.1"
archCoreTest = "2.1.0"
archComponents = "2.6.2"
activityCompose = "1.8.0"
material = "1.10.0"
fragmentKtx = "1.6.2"
permission = "1.7.1"
compose = "1.5.4"
composeViewModel = "2.6.2"
composeLifecycle = "2.6.2"
composeConstraintLayout = "1.1.0-alpha05"
firebasebom = "32.7.0"
googleServices = "4.3.15"
firebaseCrashlytics = "2.9.9"
firebaseAppDistribution = "3.2.0"
timber = "5.0.1"
ktor = "2.3.1"
soracard = "0.1.69"
xnetworking = "0.2.4"
xsubstrate = "1.1.3"
uicore = "0.2.16"
xbackup = "1.1.4"
xcrypto = "1.1.4"
ed = "2.0.1"
xerces = "2.9.0"
dagger = "2.48"
hiltCompose = "1.1.0"
hiltWorkManager = "1.0.0"
webSocketLib = "2.14"
web3j = "4.6.0-android"
zXing = "3.3.3"
zXingEmbedded = "4.3.0"
activityKtx = "1.7.1"
xserializationjson = "1.5.1"
gson = "2.10.1"
datastore = "1.0.0"
room = "2.6.0"
lazySodium = "5.0.2"
jna = "5.8.0"

[libraries]
roomDep = { module = "androidx.room:room-runtime", version.ref = "room" }
roomKaptDep = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtxDep = { module = "androidx.room:room-ktx", version.ref = "room" }
roomTestHelpersDep = { module = "androidx.room:room-testing", version.ref = "room" }
datastoreDep = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
gsonDep = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinxSerializationJsonDep = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "xserializationjson" }
activityKtxDep = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
zXingCoreDep = { module = "com.google.zxing:core", version.ref = "zXing" }
zXingEmbeddedDep = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zXingEmbedded" }
webSocketLibDep = { module = "com.neovisionaries:nv-websocket-client", version.ref = "webSocketLib" }
web3jDep = { module = "org.web3j:core", version.ref = "web3j" }
coroutineDep = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutineAndroidDep = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutineTestDep = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
daggerDep = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
daggerKaptDep = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hiltUiTestDep = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
hiltNavComposeDep = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltCompose" }
hiltWorkManagerDep = { module = "androidx.hilt:hilt-work", version.ref = "hiltWorkManager" }
hiltWorkManagerKaptDep = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWorkManager" }
lazySodiumDep = { module = "com.goterl:lazysodium-android", version.ref = "lazySodium" }
jnaDep = { module = "net.java.dev.jna:jna", version.ref = "jna" }
ktorWebSocketDep = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
soraCardDep = { module = "jp.co.soramitsu:android-sora-card", version.ref = "soracard" }
xnetworkingDep = { module = "jp.co.soramitsu.xnetworking:basic-android", version.ref = "xnetworking" }
xnetworkingSoraWalletDep = { module = "jp.co.soramitsu.xnetworking:sorawallet-android", version.ref = "xnetworking" }
xsubstrateDep = { module = "jp.co.soramitsu:xsubstrate", version.ref = "xsubstrate" }
uiCoreDep = { module = "jp.co.soramitsu:ui-core", version.ref = "uicore" }
xbackupDep = { module = "jp.co.soramitsu:xbackup", version.ref = "xbackup" }
xcryptoDep = { module = "jp.co.soramitsu:x-crypto", version.ref = "xcrypto" }
ed25519Dep = { module = "com.github.warchant:ed25519-sha3-java", version.ref = "ed" }
xercesDep = { module = "org.eclipse.birt.runtime.3_7_1:org.apache.xerces", version.ref = "xerces" }
timberDep = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
workManagerDep = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
insetterDep = { module = "dev.chrisbanes.insetter:insetter", version.ref = "insetter" }
appcompatDep = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appcompatResDep = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
constraintDep = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint" }
biometricDep = { module = "androidx.biometric:biometric", version.ref = "biometric" }
navigationFragmentDep = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigationUiDep = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigationComposeDep = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
lottieDep = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
jdenticonDep = { module = "com.github.WycliffeAssociates:jdenticon-kotlin", version.ref = "jdenticon" }
svgDep = { module = "com.caverock:androidsvg-aar", version.ref = "svg" }
coilDep = { module = "io.coil-kt:coil", version.ref = "coil" }
coilSvgDep = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coilComposeDep = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
googleFirebaseBomDep = { module = "com.google.firebase:firebase-bom", version.ref = "firebasebom" }
googleCrashlyticsDep = { module = "com.google.firebase:firebase-crashlytics" }
firebaseAnalyticsDep = { module = "com.google.firebase:firebase-analytics" }
coreKtxDep = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
archFragmentTestDep = { module = "androidx.fragment:fragment-testing", version.ref = "archFragmentTest" }
mockkDep = { module = "io.mockk:mockk", version.ref = "mockk" }
truthDep = { module = "com.google.truth:truth", version.ref = "truth" }
mockitoKotlinDep = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockitoDep = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
junitDep = { module = "junit:junit", version.ref = "junit" }
androidxTestExtJunitDep = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
androidxTestEspressoCoreDep = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspressoCore" }
archCoreTestDep = { module = "androidx.arch.core:core-testing", version.ref = "archCoreTest" }
composeActivityDep = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
materialDep = { group = "com.google.android.material", name = "material", version.ref = "material" }
composeRuntimeDep = { group = "androidx.compose.runtime", name = "runtime", version.ref = "compose" }
composeUiDep = { group = "androidx.compose.ui", name = "ui", version.ref = "compose" }
composeViewModelDep = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "composeViewModel" }
composeLifecycleDep = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "composeLifecycle" }
composeLiveDataDep = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "compose" }
composeFoundationDep = { group = "androidx.compose.foundation", name = "foundation", version.ref = "compose" }
composeToolingDep = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose" }
composeToolingPreviewDep = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose" }
composeMaterialDep = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
composeAnimationDep = { group = "androidx.compose.animation", name = "animation", version.ref = "compose" }
composeAnimationGraphicsDep = { group = "androidx.compose.animation", name = "animation-graphics", version.ref = "compose" }
composeConstraintLayoutDep = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintLayout" }
composeUiGraphicsDep = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "compose" }
#ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
#ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
#androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
#espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycleProcessDep = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "archComponents" }
lifecycleKaptDep = { group = "androidx.lifecycle", name = "lifecycle-compiler", version.ref = "archComponents" }
viewmodelKtxDep = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "archComponents" }
livedataKtxDep = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "archComponents" }
runtimeKtxDep = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "archComponents" }
fragmentKtxDep = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
permissionsRuntimeDep = { module = "com.guolindev.permissionx:permissionx", version.ref = "permission" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
googleServicesPlugin = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebaseCrashlyticsPlugin = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebaseAppDistributionPlugin = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppDistribution" }
