[versions]
agp = "9.2.1"
kotlin = "2.3.21"
ksp = "2.3.6"
appcompat = "1.7.1"
coroutines = "1.10.2"
coreKtx = "1.17.0"
constraint = "2.2.1"
biometric = "1.1.0"
navigation = "2.9.6"
navigationCompose = "2.9.6"
lottie = "4.2.0"
insetter = "0.6.1"
workManager = "2.11.0"
coil = "2.7.0"
svg = "1.4"
jdenticon = "1.1"
archFragmentTest = "1.8.9"
mockk = "1.13.11"
truth = "1.4.2"
mockitoKotlin = "6.1.0"
mockito = "5.20.0"
junit = "4.13.2"
androidxTestExtJunit = "1.3.0"
androidxTestEspressoCore = "3.7.0"
archCoreTest = "2.2.0"
archComponents = "2.10.0"
activityCompose = "1.12.1"
material = "1.12.0"
fragmentKtx = "1.8.9"
permission = "1.7.1"
compose-bom = "2026.05.00"
composeLifecycle = "2.10.0"
composeConstraintLayout = "1.1.1"
firebasebom = "34.6.0"
googleServices = "4.4.4"
firebaseCrashlytics = "3.0.6"
firebaseAppDistribution = "5.2.0"
tripletVersion = "4.0.0"
timber = "5.0.1"
ktor = "2.3.1"
ed = "2.0.1"
xerces = "2.9.0"
bouncycastle = "1.78.1"
dagger = "2.59.2"
hiltCompose = "1.3.0"
hiltWorkManager = "1.3.0"
webSocketLib = "2.14"
web3j = "4.6.0-android"
zXing = "3.3.3"
zXingEmbedded = "4.3.0"
activityKtx = "1.12.1"
xserializationjson = "1.9.0"
gson = "2.13.2"
datastore = "1.1.7"
room = "2.8.4"
lazySodium = "5.0.2"
jna = "5.8.0"
kover = "0.9.8"
soramitsuSoracard = "1.2.1-K2"
soramitsuXnetworking = "1.0.15-K2"
soramitsuXsubstrate = "1.2.7"
soramitsuUicore = "0.2.39"
soramitsuXbackup = "1.2.3"
soramitsuXcrypto = "1.2.7"
soramitsuAndroidFoundation = "0.0.4"

[libraries]
soramitsu-android-foundation = { module = "jp.co.soramitsu:android-foundation", version.ref = "soramitsuAndroidFoundation" }
soramitsu-sora-card = { module = "jp.co.soramitsu:android-sora-card", version.ref = "soramitsuSoracard" }
xnetworkingLibDep = { module = "jp.co.soramitsu.xnetworking:lib-android", version.ref = "soramitsuXnetworking" }
xsubstrateDep = { module = "jp.co.soramitsu:xsubstrate", version.ref = "soramitsuXsubstrate" }
uiCoreDep = { module = "jp.co.soramitsu:ui-core", version.ref = "soramitsuUicore" }
xbackupDep = { module = "jp.co.soramitsu:xbackup", version.ref = "soramitsuXbackup" }
xcryptoDep = { module = "jp.co.soramitsu:xcrypto", version.ref = "soramitsuXcrypto" }
roomDep = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompilerDep = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtxDep = { module = "androidx.room:room-ktx", version.ref = "room" }
roomTestHelpersDep = { module = "androidx.room:room-testing", version.ref = "room" }
datastoreDep = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
gsonDep = { module = "com.google.code.gson:gson", version.ref = "gson" }
kotlinxSerializationJsonDep = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "xserializationjson" }
activityKtxDep = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
zXingCoreDep = { module = "com.google.zxing:core", version.ref = "zXing" }
zXingEmbeddedDep = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zXingEmbedded" }
webSocketLibDep = { module = "com.neovisionaries:nv-websocket-client", version.ref = "webSocketLib" }
web3jDep = { module = "org.web3j:core", version.ref = "web3j" }
coroutineDep = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutineAndroidDep = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutineTestDep = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
daggerDep = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hiltCompilerDep = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hiltUiTestDep = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
hiltNavComposeDep = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltCompose" }
hiltWorkManagerDep = { module = "androidx.hilt:hilt-work", version.ref = "hiltWorkManager" }
hiltWorkManagerCompilerDep = { module = "androidx.hilt:hilt-compiler", version.ref = "hiltWorkManager" }
lazySodiumDep = { module = "com.goterl:lazysodium-android", version.ref = "lazySodium" }
jnaDep = { module = "net.java.dev.jna:jna", version.ref = "jna" }
ktorLoggingDep = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktorContentNegotiationDep = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktorOkHttpDep = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktorWebSocketDep = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ed25519Dep = { module = "com.github.warchant:ed25519-sha3-java", version.ref = "ed" }
xercesDep = { module = "org.eclipse.birt.runtime.3_7_1:org.apache.xerces", version.ref = "xerces" }
bcprovDep = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
timberDep = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
workManagerDep = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
insetterDep = { module = "dev.chrisbanes.insetter:insetter", version.ref = "insetter" }
appcompatDep = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appcompatResDep = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
constraintDep = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint" }
biometricDep = { module = "androidx.biometric:biometric", version.ref = "biometric" }
navigationFragmentDep = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigationUiDep = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigationComposeDep = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
lottieDep = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
jdenticonDep = { module = "com.github.WycliffeAssociates:jdenticon-kotlin", version.ref = "jdenticon" }
svgDep = { module = "com.caverock:androidsvg-aar", version.ref = "svg" }
coilDep = { module = "io.coil-kt:coil", version.ref = "coil" }
coilSvgDep = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
coilComposeDep = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
googleFirebaseBomDep = { module = "com.google.firebase:firebase-bom", version.ref = "firebasebom" }
googleCrashlyticsDep = { module = "com.google.firebase:firebase-crashlytics" }
firebaseAnalyticsDep = { module = "com.google.firebase:firebase-analytics" }
coreKtxDep = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
archFragmentTestDep = { module = "androidx.fragment:fragment-testing", version.ref = "archFragmentTest" }
mockkDep = { module = "io.mockk:mockk", version.ref = "mockk" }
mockkAndroidDep = { module = "io.mockk:mockk-android", version.ref = "mockk" }
truthDep = { module = "com.google.truth:truth", version.ref = "truth" }
mockitoKotlinDep = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
mockitoDep = { module = "org.mockito:mockito-core", version.ref = "mockito" }
junitDep = { module = "junit:junit", version.ref = "junit" }
androidxTestExtJunitDep = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
androidxTestEspressoCoreDep = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspressoCore" }
androidxTestEspressoIntentsDep = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidxTestEspressoCore" }
archCoreTestDep = { module = "androidx.arch.core:core-testing", version.ref = "archCoreTest" }
composeActivityDep = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
materialDep = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
composeRuntimeDep = { group = "androidx.compose.runtime", name = "runtime" }
composeUiDep = { group = "androidx.compose.ui", name = "ui" }
composeViewModelDep = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose" }
composeLifecycleDep = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "composeLifecycle" }
composeLiveDataDep = { group = "androidx.compose.runtime", name = "runtime-livedata" }
composeFoundationDep = { group = "androidx.compose.foundation", name = "foundation" }
composeToolingDep = { group = "androidx.compose.ui", name = "ui-tooling" }
composeToolingPreviewDep = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
composeMaterialDep = { group = "androidx.compose.material", name = "material" }
composeMaterial3Dep = { group = "androidx.compose.material3", name = "material3" }
composeAnimationDep = { group = "androidx.compose.animation", name = "animation" }
composeAnimationGraphicsDep = { group = "androidx.compose.animation", name = "animation-graphics" }
composeConstraintLayoutDep = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "composeConstraintLayout" }
composeUiGraphicsDep = { group = "androidx.compose.ui", name = "ui-graphics" }
composeUiTestManifestDep = { group = "androidx.compose.ui", name = "ui-test-manifest" }
composeUiTestJunit4Dep = { group = "androidx.compose.ui", name = "ui-test-junit4" }
#androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
#espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycleProcessDep = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "archComponents" }
viewmodelKtxDep = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "archComponents" }
livedataKtxDep = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "archComponents" }
runtimeKtxDep = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "archComponents" }
fragmentKtxDep = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
permissionsRuntimeDep = { module = "com.guolindev.permissionx:permissionx", version.ref = "permission" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
googleServicesPlugin = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebaseCrashlyticsPlugin = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebaseAppDistributionPlugin = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppDistribution" }
triplet = { id = "com.github.triplet.play", version.ref = "tripletVersion" }
